version: '3'
services:
  web1:
      image: php:7.2-fpm
      container_name: web1
      depends_on:
        - mysql
      ports:
        - 81:80
      volumes:
        - ./html/web1:/var/www/html
  web2:
      image: php:7.2-fpm
      container_name: web2
      depends_on:
        - mysql
      ports:
        - 82:80
      volumes:
        - ./html/web2:/var/www/html
  nginx:
      image: nginx
      ports:
        - 80:80
        - 443:443
      links:
        - web1
        - web2
      volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./html:/var/www/html
      depends_on:
        - web1
        - web2
  mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: sample
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
      ports:
        - 3306:3306
      volumes:
        - ./docker/mysql/init:/docker-entrypoint-initdb.d
        - ./var/lib/mysql:/var/lib/mysql
