version: '3'
services:
  web:
    image: nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./var/www/html:/var/www/html
  app:
    image: php:7.3.2-fpm
    volumes:
      - ./var/www/html:/var/www/html
